### PR TITLE
Add linter for OpenApi and grpc proto in github actions CI

### LINKED ISSUE #10: Add linter github actions for the repo
https://github.com/marketplace/actions/openapi-lint-action

### PR DESCRIPTION
**Pull request by sivanantha321**
Fixes #10

### CODE REVIEW

**Review by adriangonz — COMMENTED** [review]
Nice one @sivanantha321 ! We've been wanting to add an OpenAPI linter for a while.

Out of curiosity, couldn't we just use one of the existing OpenAPI linters in available in the GH Actions marketplace? These tend to work well, and would reduce the maintenance burden of having to maintain our own action.

**Comment by sivanantha321** [comment]
> Nice one @sivanantha321 ! We've been wanting to add an OpenAPI linter for a while.
> 
> Out of curiosity, couldn't we just use one of the existing OpenAPI linters in available in the GH Actions marketplace? These tend to work well, and would reduce the maintenance burden of having to maintain our own action.

@adriangonz I do agree with you interms of maintenance. Most of the linters available in the github actions is unmaintained. I tried using the [openapi-lint-action](https://github.com/marketplace/actions/openapi-lint-action) which seemed better than other actions available. But it didn't have support for ignoring lint errors. So I modified the code to add support for ignoring lint errors. Btw, this action is also unmaintained. If you happen to come across a better linter action, I'd greatly appreciate your recommendation :).

**Comment by adriangonz** [comment]
I can see that the `openapi-lint-action` repo seems maintained, so I'd be more keen towards using that instead of having one within the repo. 

Wouldn't it be good to raise those lint errors anyway?

**Review by adriangonz — APPROVED** [review]
That's a great idea @sivanantha321 ! Nice one on using `redocly` for the linting instead of any of the non-ideal GH actions.

**Review by yuzisun — APPROVED** [review]

**Pull request merged**
